***
# Machine Learning Linear Regression Model 3 
### Time-Series Forecast of the Average-Annual of Maternal Mortality & Associated Impacts in USA (2009-2030)
***

### Importing Dependencies

In [1]:
# Importing dependencies:
import numpy as np
import pandas as pd

### Read the CSV and Perform Basic Data Cleaning

In [2]:
# Reading the csv file into a pandas DataFrame
mmr_without_race = pd.read_csv('../Resources/non_race_data.csv')
mmr_without_race

,year,state,id,state_code,latitude,longitude,deaths,births,maternal_mortality_ratio,population,...,prem_death_val,smoking_val,uninsured_val,all_determs_val,all_outcomes_val,chlamydia_val,prem_death_ri_val,teen_birth_val,primary_care_val,low_birthweight_val
0,2015,Alabama,US.AL,AL,32.318231,-86.902298,12.0,59657.0,20.11,2505795.0,...,10095.0,21.1,12.9,-0.371,-0.325,611.0,1.2,34.3,103.5,10.0
1,2016,Alabama,US.AL,AL,32.318231,-86.902298,35.0,59151.0,59.17,2507714.0,...,10097.0,21.4,11.1,-0.427,-0.366,600.2,1.1,32.0,116.4,10.1
2,2017,Alabama,US.AL,AL,32.318231,-86.902298,41.0,58941.0,69.56,2514911.0,...,10321.0,21.5,9.6,-0.427,-0.335,543.6,1.2,30.1,119.3,10.4
3,2018,Alabama,US.AL,AL,32.318231,-86.902298,31.0,57761.0,53.67,2523756.0,...,10720.0,20.9,9.3,-0.483,-0.356,553.6,1.1,28.4,122.8,10.3
4,2019,Alabama,US.AL,AL,32.318231,-86.902298,35.0,58615.0,59.71,2533668.0,...,10435.0,19.2,9.7,-0.437,-0.383,614.1,1.2,27.0,122.8,10.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,2014,Wisconsin,US.WI,WI,43.784440,-88.787868,16.0,67161.0,23.82,2898057.0,...,6207.0,18.7,9.0,0.165,0.067,415.4,2.0,21.9,125.0,7.1
304,2015,Wisconsin,US.WI,WI,43.784440,-88.787868,11.0,67041.0,16.41,2903737.0,...,6365.0,17.4,8.2,0.146,0.046,411.6,1.9,19.6,125.3,7.0
305,2016,Wisconsin,US.WI,WI,43.784440,-88.787868,15.0,66615.0,22.52,2905282.0,...,6324.0,17.3,6.5,0.114,0.106,403.2,1.9,18.0,140.3,7.3
306,2017,Wisconsin,US.WI,WI,43.784440,-88.787868,12.0,64975.0,18.47,2912745.0,...,6437.0,17.1,5.5,0.201,0.072,423.5,1.9,16.2,145.2,7.3
307,2019,Wisconsin,US.WI,WI,43.784440,-88.787868,13.0,63270.0,20.55,2925225.0,...,6800.0,16.4,5.5,0.129,0.074,478.6,2.0,13.8,152.4,7.7

In [3]:
mmr_without_race.columns

Index(['year', 'state', 'id', 'state_code', 'latitude', 'longitude', 'deaths',
       'births', 'maternal_mortality_ratio', 'population', 'employer',
       'non_group', 'medicaid', 'medicare', 'military', 'uninsured',
       'air_pollution_val', 'cancer_death_val', 'cardio_death_val',
       'child_pov_val', 'choles_check_val', 'dent_vis_val', 'dentists_val',
       'diabetes_val', 'drug_deaths_val', 'health_stat_fem_val',
       'immun_child_val', 'income_ineq_val', 'infant_mort_val',
       'infect_dis_val', 'obesity_val', 'phys_inac_val', 'prem_death_val',
       'smoking_val', 'uninsured_val', 'all_determs_val', 'all_outcomes_val',
       'chlamydia_val', 'prem_death_ri_val', 'teen_birth_val',
       'primary_care_val', 'low_birthweight_val'],
      dtype='object')

### Grouping DataFrame by `year` and Calculating the Average

In [4]:
# Setting y value for grouping
y = 'maternal_mortality_ratio'

# Grouping by year
AVG_MMR_USA = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA.reset_index()

    year  maternal_mortality_ratio
0   2009                 26.747083
1   2010                 25.715417
2   2011                 27.871481
3   2012                 29.929583
4   2013                 31.729333
5   2014                 32.339259
6   2015                 31.944074
7   2016                 35.440968
8   2017                 34.208889
9   2018                 31.526071
10  2019                 34.073333

In [5]:
# Setting y value for grouping
y = 'diabetes_val'

# Grouping by year
AVG_MMR_USA_1 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_1.reset_index()

# Merging with mmr_predictions 
df_1 = pd.merge(AVG_MMR_USA, AVG_MMR_USA_1, how='inner', left_on=['year'], right_on=['year'])
df_1.reset_index()

    year  maternal_mortality_ratio  diabetes_val
0   2009                 26.747083      8.920833
1   2010                 25.715417      9.291667
2   2011                 27.871481      9.229630
3   2012                 29.929583     10.208333
4   2013                 31.729333     10.200000
5   2014                 32.339259     10.070370
6   2015                 31.944074     10.677778
7   2016                 35.440968     10.670968
8   2017                 34.208889     10.869444
9   2018                 31.526071     11.514286
10  2019                 34.073333     11.653333

In [6]:
# Setting y value for grouping
y = 'prem_death_val'

# Grouping by year
AVG_MMR_USA_2 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_2.reset_index()

# Merging with mmr_predictions 
df_2 = pd.merge(df_1, AVG_MMR_USA_2, how='inner', left_on=['year'], right_on=['year'])
df_2.reset_index()

    year  maternal_mortality_ratio  diabetes_val  prem_death_val
0   2009                 26.747083      8.920833     7845.041667
1   2010                 25.715417      9.291667     7816.875000
2   2011                 27.871481      9.229630     7603.666667
3   2012                 29.929583     10.208333     8014.041667
4   2013                 31.729333     10.200000     7635.300000
5   2014                 32.339259     10.070370     7233.481481
6   2015                 31.944074     10.677778     7530.666667
7   2016                 35.440968     10.670968     7582.193548
8   2017                 34.208889     10.869444     7658.861111
9   2018                 31.526071     11.514286     8270.428571
10  2019                 34.073333     11.653333     8077.366667

In [7]:
# Setting y value for grouping
y = 'phys_inac_val'

# Grouping by year
AVG_MMR_USA_3 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_3.reset_index()

# Merging with mmr_predictions 
df_3 = pd.merge(df_2, AVG_MMR_USA_3, how='inner', left_on=['year'], right_on=['year'])
df_3.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val
0,2009,26.747083,8.920833,7845.041667,25.879167
1,2010,25.715417,9.291667,7816.875000,25.350000
2,2011,27.871481,9.229630,7603.666667,24.644444
3,2012,29.929583,10.208333,8014.041667,27.183333
4,2013,31.729333,10.200000,7635.300000,23.720000
5,2014,32.339259,10.070370,7233.481481,26.818519
6,2015,31.944074,10.677778,7530.666667,24.177778
7,2016,35.440968,10.670968,7582.193548,27.041935
8,2017,34.208889,10.869444,7658.861111,24.272222
9,2018,31.526071,11.514286,8270.428571,28.246429
10,2019,34.073333,11.653333,8077.366667,25.070000

In [8]:
# Setting y value for grouping
y = 'low_birthweight_val'

# Grouping by year
AVG_MMR_USA_4 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_4.reset_index()

# Merging with mmr_predictions 
df_4 = pd.merge(df_3, AVG_MMR_USA_4, how='inner', left_on=['year'], right_on=['year'])
df_4.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000

In [9]:
# Setting y value for grouping
y = 'obesity_val'

# Grouping by year
AVG_MMR_USA_5 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_5.reset_index()

# Merging with mmr_predictions 
df_5 = pd.merge(df_4, AVG_MMR_USA_5, how='inner', left_on=['year'], right_on=['year'])
df_5.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667

In [10]:
# Setting y value for grouping
y = 'cardio_death_val'

# Grouping by year
AVG_MMR_USA_6 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_6.reset_index()

# Merging with mmr_predictions 
df_6 = pd.merge(df_5, AVG_MMR_USA_6, how='inner', left_on=['year'], right_on=['year'])
df_6.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000

In [11]:
# Setting y value for grouping
y = 'medicare'

# Grouping by year
AVG_MMR_USA_7 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_7.reset_index()

# Merging with mmr_predictions 
df_7 = pd.merge(df_6, AVG_MMR_USA_7, how='inner', left_on=['year'], right_on=['year'])
df_7.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333

In [12]:
# Setting y value for grouping
y = 'cancer_death_val'

# Grouping by year
AVG_MMR_USA_8 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_8.reset_index()

# Merging with mmr_predictions 
df_8 = pd.merge(df_7, AVG_MMR_USA_8, how='inner', left_on=['year'], right_on=['year'])
df_8.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333

In [13]:
# Setting y value for grouping
y = 'chlamydia_val'

# Grouping by year
AVG_MMR_USA_9 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_9.reset_index()

# Merging with mmr_predictions 
df_9 = pd.merge(df_8, AVG_MMR_USA_9, how='inner', left_on=['year'], right_on=['year'])
df_9.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333

In [14]:
# Setting y value for grouping
y = 'child_pov_val'

# Grouping by year
AVG_MMR_USA_10 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_10.reset_index()

# Merging with mmr_predictions 
df_10 = pd.merge(df_9, AVG_MMR_USA_10, how='inner', left_on=['year'], right_on=['year'])
df_10.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833,18.529167
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167,21.225000
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444,21.255556
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500,21.679167
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667,21.450000
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778,18.859259
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852,21.644444
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548,19.541935
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556,17.900000
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714,20.500000
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333,18.380000

In [15]:
# Setting y value for grouping
y = 'smoking_val'

# Grouping by year
AVG_MMR_USA_11 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_11.reset_index()

# Merging with mmr_predictions 
df_11 = pd.merge(df_10, AVG_MMR_USA_11, how='inner', left_on=['year'], right_on=['year'])
df_11.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833,18.529167,19.641667
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167,21.225000,19.166667
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444,21.255556,18.140741
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500,21.679167,21.633333
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667,21.450000,20.163333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778,18.859259,19.103704
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852,21.644444,18.685185
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548,19.541935,18.270968
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556,17.900000,17.386111
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714,20.500000,18.246429
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333,18.380000,16.740000

In [16]:
# Setting y value for grouping
y = 'infant_mort_val'

# Grouping by year
AVG_MMR_USA_12 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_12.reset_index()

# Merging with mmr_predictions 
df_12 = pd.merge(df_11, AVG_MMR_USA_12, how='inner', left_on=['year'], right_on=['year'])
df_12.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833,18.529167,19.641667,7.254167
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167,21.225000,19.166667,7.120833
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444,21.255556,18.140741,6.744444
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500,21.679167,21.633333,6.816667
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667,21.450000,20.163333,6.460000
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778,18.859259,19.103704,6.266667
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852,21.644444,18.685185,6.385185
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548,19.541935,18.270968,6.274194
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556,17.900000,17.386111,6.097222
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714,20.500000,18.246429,6.442857
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333,18.380000,16.740000,6.326667

In [17]:
# Setting y value for grouping
y = 'income_ineq_val'

# Grouping by year
AVG_MMR_USA_13 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_13.reset_index()

# Merging with mmr_predictions 
df_13 = pd.merge(df_12, AVG_MMR_USA_13, how='inner', left_on=['year'], right_on=['year'])
df_13.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833,18.529167,19.641667,7.254167,4.547917
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167,21.225000,19.166667,7.120833,4.633750
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444,21.255556,18.140741,6.744444,4.691481
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500,21.679167,21.633333,6.816667,4.867083
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667,21.450000,20.163333,6.460000,4.782000
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778,18.859259,19.103704,6.266667,4.758148
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852,21.644444,18.685185,6.385185,4.812963
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548,19.541935,18.270968,6.274194,4.790323
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556,17.900000,17.386111,6.097222,4.777222
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714,20.500000,18.246429,6.442857,4.883929
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333,18.380000,16.740000,6.326667,4.746333

In [18]:
# Setting y value for grouping
y = 'dentists_val'

# Grouping by year
AVG_MMR_USA_14 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_14.reset_index()

# Merging with mmr_predictions 
df_14 = pd.merge(df_13, AVG_MMR_USA_14, how='inner', left_on=['year'], right_on=['year'])
df_14.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833,18.529167,19.641667,7.254167,4.547917,54.887500
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167,21.225000,19.166667,7.120833,4.633750,55.062500
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444,21.255556,18.140741,6.744444,4.691481,56.674074
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500,21.679167,21.633333,6.816667,4.867083,55.620833
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667,21.450000,20.163333,6.460000,4.782000,56.910000
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778,18.859259,19.103704,6.266667,4.758148,57.655556
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852,21.644444,18.685185,6.385185,4.812963,57.440741
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548,19.541935,18.270968,6.274194,4.790323,57.416129
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556,17.900000,17.386111,6.097222,4.777222,57.925000
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714,20.500000,18.246429,6.442857,4.883929,56.960714
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333,18.380000,16.740000,6.326667,4.746333,56.890000

In [19]:
# Setting y value for grouping
y = 'prem_death_ri_val'

# Grouping by year
AVG_MMR_USA_15 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_15.reset_index()

# Merging with mmr_predictions 
df_15 = pd.merge(df_14, AVG_MMR_USA_15, how='inner', left_on=['year'], right_on=['year'])
df_15.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833,18.529167,19.641667,7.254167,4.547917,54.887500,1.604167
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167,21.225000,19.166667,7.120833,4.633750,55.062500,1.504167
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444,21.255556,18.140741,6.744444,4.691481,56.674074,1.544444
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500,21.679167,21.633333,6.816667,4.867083,55.620833,1.495833
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667,21.450000,20.163333,6.460000,4.782000,56.910000,1.500000
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778,18.859259,19.103704,6.266667,4.758148,57.655556,1.503704
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852,21.644444,18.685185,6.385185,4.812963,57.440741,1.414815
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548,19.541935,18.270968,6.274194,4.790323,57.416129,1.429032
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556,17.900000,17.386111,6.097222,4.777222,57.925000,1.433333
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714,20.500000,18.246429,6.442857,4.883929,56.960714,1.414286
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333,18.380000,16.740000,6.326667,4.746333,56.890000,1.486667

In [20]:
# Setting y value for grouping
y = 'dent_vis_val'

# Grouping by year
AVG_MMR_USA_16 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_16.reset_index()

# Merging with mmr_predictions 
df_16 = pd.merge(df_15, AVG_MMR_USA_16, how='inner', left_on=['year'], right_on=['year'])
df_16.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833,18.529167,19.641667,7.254167,4.547917,54.887500,1.604167,69.491667
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167,21.225000,19.166667,7.120833,4.633750,55.062500,1.504167,68.895833
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444,21.255556,18.140741,6.744444,4.691481,56.674074,1.544444,69.488889
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500,21.679167,21.633333,6.816667,4.867083,55.620833,1.495833,68.704167
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667,21.450000,20.163333,6.460000,4.782000,56.910000,1.500000,64.690000
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778,18.859259,19.103704,6.266667,4.758148,57.655556,1.503704,65.314815
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852,21.644444,18.685185,6.385185,4.812963,57.440741,1.414815,63.455556
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548,19.541935,18.270968,6.274194,4.790323,57.416129,1.429032,64.038710
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556,17.900000,17.386111,6.097222,4.777222,57.925000,1.433333,65.522222
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714,20.500000,18.246429,6.442857,4.883929,56.960714,1.414286,64.200000
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333,18.380000,16.740000,6.326667,4.746333,56.890000,1.486667,65.383333

In [21]:
# Setting y value for grouping
y = 'all_outcomes_val'

# Grouping by year
AVG_MMR_USA_17 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_17.reset_index()

# Merging with mmr_predictions 
df_17 = pd.merge(df_16, AVG_MMR_USA_17, how='inner', left_on=['year'], right_on=['year'])
df_17.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833,18.529167,19.641667,7.254167,4.547917,54.887500,1.604167,69.491667,0.016708
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167,21.225000,19.166667,7.120833,4.633750,55.062500,1.504167,68.895833,0.012917
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444,21.255556,18.140741,6.744444,4.691481,56.674074,1.544444,69.488889,0.022185
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500,21.679167,21.633333,6.816667,4.867083,55.620833,1.495833,68.704167,-0.069458
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667,21.450000,20.163333,6.460000,4.782000,56.910000,1.500000,64.690000,-0.026767
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778,18.859259,19.103704,6.266667,4.758148,57.655556,1.503704,65.314815,-0.019296
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852,21.644444,18.685185,6.385185,4.812963,57.440741,1.414815,63.455556,-0.051185
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548,19.541935,18.270968,6.274194,4.790323,57.416129,1.429032,64.038710,-0.060258
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556,17.900000,17.386111,6.097222,4.777222,57.925000,1.433333,65.522222,-0.033944
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714,20.500000,18.246429,6.442857,4.883929,56.960714,1.414286,64.200000,-0.094500
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333,18.380000,16.740000,6.326667,4.746333,56.890000,1.486667,65.383333,-0.074867

In [22]:
# Setting y value for grouping
y = 'all_determs_val'

# Grouping by year
AVG_MMR_USA_18 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_18.reset_index()

# Merging with mmr_predictions 
df_18 = pd.merge(df_17, AVG_MMR_USA_18, how='inner', left_on=['year'], right_on=['year'])
df_18.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,383.645833,18.529167,19.641667,7.254167,4.547917,54.887500,1.604167,69.491667,0.016708,-0.055208
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,403.054167,21.225000,19.166667,7.120833,4.633750,55.062500,1.504167,68.895833,0.012917,-0.061458
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,410.344444,21.255556,18.140741,6.744444,4.691481,56.674074,1.544444,69.488889,0.022185,-0.019296
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,442.462500,21.679167,21.633333,6.816667,4.867083,55.620833,1.495833,68.704167,-0.069458,-0.098208
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,454.846667,21.450000,20.163333,6.460000,4.782000,56.910000,1.500000,64.690000,-0.026767,-0.067567
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,454.677778,18.859259,19.103704,6.266667,4.758148,57.655556,1.503704,65.314815,-0.019296,-0.028667
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,454.551852,21.644444,18.685185,6.385185,4.812963,57.440741,1.414815,63.455556,-0.051185,-0.078519
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,464.593548,19.541935,18.270968,6.274194,4.790323,57.416129,1.429032,64.038710,-0.060258,-0.057806
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,473.355556,17.900000,17.386111,6.097222,4.777222,57.925000,1.433333,65.522222,-0.033944,-0.008944
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,502.885714,20.500000,18.246429,6.442857,4.883929,56.960714,1.414286,64.200000,-0.094500,-0.082714
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,530.463333,18.380000,16.740000,6.326667,4.746333,56.890000,1.486667,65.383333,-0.074867,-0.070133

In [24]:
# Setting y value for grouping
y = 'health_stat_fem_val'

# Grouping by year
AVG_MMR_USA_19 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_19.reset_index()

# Merging with mmr_predictions 
df_19 = pd.merge(df_18, AVG_MMR_USA_19, how='inner', left_on=['year'], right_on=['year'])
df_19.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,18.529167,19.641667,7.254167,4.547917,54.887500,1.604167,69.491667,0.016708,-0.055208,52.666667
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,21.225000,19.166667,7.120833,4.633750,55.062500,1.504167,68.895833,0.012917,-0.061458,52.266667
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,21.255556,18.140741,6.744444,4.691481,56.674074,1.544444,69.488889,0.022185,-0.019296,52.937037
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,21.679167,21.633333,6.816667,4.867083,55.620833,1.495833,68.704167,-0.069458,-0.098208,49.241667
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,21.450000,20.163333,6.460000,4.782000,56.910000,1.500000,64.690000,-0.026767,-0.067567,50.263333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,18.859259,19.103704,6.266667,4.758148,57.655556,1.503704,65.314815,-0.019296,-0.028667,50.707407
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,21.644444,18.685185,6.385185,4.812963,57.440741,1.414815,63.455556,-0.051185,-0.078519,49.788889
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,19.541935,18.270968,6.274194,4.790323,57.416129,1.429032,64.038710,-0.060258,-0.057806,50.290323
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,17.900000,17.386111,6.097222,4.777222,57.925000,1.433333,65.522222,-0.033944,-0.008944,50.108333
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,20.500000,18.246429,6.442857,4.883929,56.960714,1.414286,64.200000,-0.094500,-0.082714,47.725000
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,18.380000,16.740000,6.326667,4.746333,56.890000,1.486667,65.383333,-0.074867,-0.070133,48.260000

In [25]:
# Setting y value for grouping
y = 'population'

# Grouping by year
AVG_MMR_USA_20 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_20.reset_index()

# Merging with mmr_predictions 
df_20 = pd.merge(df_19, AVG_MMR_USA_20, how='inner', left_on=['year'], right_on=['year'])
df_20.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val,population
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,19.641667,7.254167,4.547917,54.887500,1.604167,69.491667,0.016708,-0.055208,52.666667,5.119973e+06
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,19.166667,7.120833,4.633750,55.062500,1.504167,68.895833,0.012917,-0.061458,52.266667,4.994359e+06
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,18.140741,6.744444,4.691481,56.674074,1.544444,69.488889,0.022185,-0.019296,52.937037,4.826144e+06
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,21.633333,6.816667,4.867083,55.620833,1.495833,68.704167,-0.069458,-0.098208,49.241667,5.287860e+06
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,20.163333,6.460000,4.782000,56.910000,1.500000,64.690000,-0.026767,-0.067567,50.263333,4.679635e+06
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,19.103704,6.266667,4.758148,57.655556,1.503704,65.314815,-0.019296,-0.028667,50.707407,5.038078e+06
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,18.685185,6.385185,4.812963,57.440741,1.414815,63.455556,-0.051185,-0.078519,49.788889,5.095491e+06
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,18.270968,6.274194,4.790323,57.416129,1.429032,64.038710,-0.060258,-0.057806,50.290323,4.763534e+06
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,17.386111,6.097222,4.777222,57.925000,1.433333,65.522222,-0.033944,-0.008944,50.108333,4.356286e+06
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,18.246429,6.442857,4.883929,56.960714,1.414286,64.200000,-0.094500,-0.082714,47.725000,5.055135e+06
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,16.740000,6.326667,4.746333,56.890000,1.486667,65.383333,-0.074867,-0.070133,48.260000,4.878406e+06

In [26]:
# Setting y value for grouping
y = 'employer'

# Grouping by year
AVG_MMR_USA_21 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_21.reset_index()

# Merging with mmr_predictions 
df_21 = pd.merge(df_20, AVG_MMR_USA_21, how='inner', left_on=['year'], right_on=['year'])
df_21.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val,population,employer
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,7.254167,4.547917,54.887500,1.604167,69.491667,0.016708,-0.055208,52.666667,5.119973e+06,61.200000
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,7.120833,4.633750,55.062500,1.504167,68.895833,0.012917,-0.061458,52.266667,4.994359e+06,58.829167
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,6.744444,4.691481,56.674074,1.544444,69.488889,0.022185,-0.019296,52.937037,4.826144e+06,58.933333
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,6.816667,4.867083,55.620833,1.495833,68.704167,-0.069458,-0.098208,49.241667,5.287860e+06,58.395833
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,6.460000,4.782000,56.910000,1.500000,64.690000,-0.026767,-0.067567,50.263333,4.679635e+06,58.646667
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,6.266667,4.758148,57.655556,1.503704,65.314815,-0.019296,-0.028667,50.707407,5.038078e+06,59.433333
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,6.385185,4.812963,57.440741,1.414815,63.455556,-0.051185,-0.078519,49.788889,5.095491e+06,59.274074
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,6.274194,4.790323,57.416129,1.429032,64.038710,-0.060258,-0.057806,50.290323,4.763534e+06,60.029032
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,6.097222,4.777222,57.925000,1.433333,65.522222,-0.033944,-0.008944,50.108333,4.356286e+06,60.475000
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,6.442857,4.883929,56.960714,1.414286,64.200000,-0.094500,-0.082714,47.725000,5.055135e+06,60.146429
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,6.326667,4.746333,56.890000,1.486667,65.383333,-0.074867,-0.070133,48.260000,4.878406e+06,61.250000

In [27]:
# Setting y value for grouping
y = 'non_group'

# Grouping by year
AVG_MMR_USA_22 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_22.reset_index()

# Merging with mmr_predictions 
df_22 = pd.merge(df_21, AVG_MMR_USA_22, how='inner', left_on=['year'], right_on=['year'])
df_22.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val,population,employer,non_group
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,4.547917,54.887500,1.604167,69.491667,0.016708,-0.055208,52.666667,5.119973e+06,61.200000,6.295833
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,4.633750,55.062500,1.504167,68.895833,0.012917,-0.061458,52.266667,4.994359e+06,58.829167,6.262500
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,4.691481,56.674074,1.544444,69.488889,0.022185,-0.019296,52.937037,4.826144e+06,58.933333,6.155556
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,4.867083,55.620833,1.495833,68.704167,-0.069458,-0.098208,49.241667,5.287860e+06,58.395833,6.158333
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,4.782000,56.910000,1.500000,64.690000,-0.026767,-0.067567,50.263333,4.679635e+06,58.646667,6.656667
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,4.758148,57.655556,1.503704,65.314815,-0.019296,-0.028667,50.707407,5.038078e+06,59.433333,8.374074
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,4.812963,57.440741,1.414815,63.455556,-0.051185,-0.078519,49.788889,5.095491e+06,59.274074,9.174074
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,4.790323,57.416129,1.429032,64.038710,-0.060258,-0.057806,50.290323,4.763534e+06,60.029032,9.045161
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,4.777222,57.925000,1.433333,65.522222,-0.033944,-0.008944,50.108333,4.356286e+06,60.475000,8.341667
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,4.883929,56.960714,1.414286,64.200000,-0.094500,-0.082714,47.725000,5.055135e+06,60.146429,7.667857
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,4.746333,56.890000,1.486667,65.383333,-0.074867,-0.070133,48.260000,4.878406e+06,61.250000,7.643333

In [28]:
# Setting y value for grouping
y = 'medicaid'

# Grouping by year
AVG_MMR_USA_23 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_23.reset_index()

# Merging with mmr_predictions 
df_23 = pd.merge(df_22, AVG_MMR_USA_23, how='inner', left_on=['year'], right_on=['year'])
df_23.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val,population,employer,non_group,medicaid
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,54.887500,1.604167,69.491667,0.016708,-0.055208,52.666667,5.119973e+06,61.200000,6.295833,11.237500
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,55.062500,1.504167,68.895833,0.012917,-0.061458,52.266667,4.994359e+06,58.829167,6.262500,11.750000
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,56.674074,1.544444,69.488889,0.022185,-0.019296,52.937037,4.826144e+06,58.933333,6.155556,12.459259
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,55.620833,1.495833,68.704167,-0.069458,-0.098208,49.241667,5.287860e+06,58.395833,6.158333,12.500000
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,56.910000,1.500000,64.690000,-0.026767,-0.067567,50.263333,4.679635e+06,58.646667,6.656667,12.240000
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,57.655556,1.503704,65.314815,-0.019296,-0.028667,50.707407,5.038078e+06,59.433333,8.374074,14.014815
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,57.440741,1.414815,63.455556,-0.051185,-0.078519,49.788889,5.095491e+06,59.274074,9.174074,15.714815
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,57.416129,1.429032,64.038710,-0.060258,-0.057806,50.290323,4.763534e+06,60.029032,9.045161,16.738710
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,57.925000,1.433333,65.522222,-0.033944,-0.008944,50.108333,4.356286e+06,60.475000,8.341667,17.030556
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,56.960714,1.414286,64.200000,-0.094500,-0.082714,47.725000,5.055135e+06,60.146429,7.667857,17.400000
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,56.890000,1.486667,65.383333,-0.074867,-0.070133,48.260000,4.878406e+06,61.250000,7.643333,15.776667

In [29]:
# Setting y value for grouping
y = 'military'

# Grouping by year
AVG_MMR_USA_24 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_24.reset_index()

# Merging with mmr_predictions 
df_24 = pd.merge(df_23, AVG_MMR_USA_24, how='inner', left_on=['year'], right_on=['year'])
df_24.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val,population,employer,non_group,medicaid,military
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,1.604167,69.491667,0.016708,-0.055208,52.666667,5.119973e+06,61.200000,6.295833,11.237500,1.545833
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,1.504167,68.895833,0.012917,-0.061458,52.266667,4.994359e+06,58.829167,6.262500,11.750000,1.504167
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,1.544444,69.488889,0.022185,-0.019296,52.937037,4.826144e+06,58.933333,6.155556,12.459259,1.596296
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,1.495833,68.704167,-0.069458,-0.098208,49.241667,5.287860e+06,58.395833,6.158333,12.500000,1.658333
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,1.500000,64.690000,-0.026767,-0.067567,50.263333,4.679635e+06,58.646667,6.656667,12.240000,1.753333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,1.503704,65.314815,-0.019296,-0.028667,50.707407,5.038078e+06,59.433333,8.374074,14.014815,1.637037
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,1.414815,63.455556,-0.051185,-0.078519,49.788889,5.095491e+06,59.274074,9.174074,15.714815,1.670370
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,1.429032,64.038710,-0.060258,-0.057806,50.290323,4.763534e+06,60.029032,9.045161,16.738710,1.619355
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,1.433333,65.522222,-0.033944,-0.008944,50.108333,4.356286e+06,60.475000,8.341667,17.030556,1.588889
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,1.414286,64.200000,-0.094500,-0.082714,47.725000,5.055135e+06,60.146429,7.667857,17.400000,1.600000
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,1.486667,65.383333,-0.074867,-0.070133,48.260000,4.878406e+06,61.250000,7.643333,15.776667,1.643333

In [30]:
# Setting y value for grouping
y = 'uninsured'

# Grouping by year
AVG_MMR_USA_25 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_25.reset_index()

# Merging with mmr_predictions 
df_25 = pd.merge(df_24, AVG_MMR_USA_25, how='inner', left_on=['year'], right_on=['year'])
df_25.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val,population,employer,non_group,medicaid,military,uninsured
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,69.491667,0.016708,-0.055208,52.666667,5.119973e+06,61.200000,6.295833,11.237500,1.545833,17.662500
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,68.895833,0.012917,-0.061458,52.266667,4.994359e+06,58.829167,6.262500,11.750000,1.504167,19.566667
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,69.488889,0.022185,-0.019296,52.937037,4.826144e+06,58.933333,6.155556,12.459259,1.596296,18.740741
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,68.704167,-0.069458,-0.098208,49.241667,5.287860e+06,58.395833,6.158333,12.500000,1.658333,19.108333
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,64.690000,-0.026767,-0.067567,50.263333,4.679635e+06,58.646667,6.656667,12.240000,1.753333,18.503333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,65.314815,-0.019296,-0.028667,50.707407,5.038078e+06,59.433333,8.374074,14.014815,1.637037,14.344444
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,63.455556,-0.051185,-0.078519,49.788889,5.095491e+06,59.274074,9.174074,15.714815,1.670370,11.785185
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,64.038710,-0.060258,-0.057806,50.290323,4.763534e+06,60.029032,9.045161,16.738710,1.619355,10.209677
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,65.522222,-0.033944,-0.008944,50.108333,4.356286e+06,60.475000,8.341667,17.030556,1.588889,10.311111
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,64.200000,-0.094500,-0.082714,47.725000,5.055135e+06,60.146429,7.667857,17.400000,1.600000,10.825000
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,65.383333,-0.074867,-0.070133,48.260000,4.878406e+06,61.250000,7.643333,15.776667,1.643333,11.423333

In [31]:
# Setting y value for grouping
y = 'air_pollution_val'

# Grouping by year
AVG_MMR_USA_26 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_26.reset_index()

# Merging with mmr_predictions 
df_26 = pd.merge(df_25, AVG_MMR_USA_26, how='inner', left_on=['year'], right_on=['year'])
df_26.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,all_outcomes_val,all_determs_val,health_stat_fem_val,population,employer,non_group,medicaid,military,uninsured,air_pollution_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,0.016708,-0.055208,52.666667,5.119973e+06,61.200000,6.295833,11.237500,1.545833,17.662500,11.887500
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,0.012917,-0.061458,52.266667,4.994359e+06,58.829167,6.262500,11.750000,1.504167,19.566667,11.387500
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,0.022185,-0.019296,52.937037,4.826144e+06,58.933333,6.155556,12.459259,1.596296,18.740741,10.503704
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,-0.069458,-0.098208,49.241667,5.287860e+06,58.395833,6.158333,12.500000,1.658333,19.108333,10.429167
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,-0.026767,-0.067567,50.263333,4.679635e+06,58.646667,6.656667,12.240000,1.753333,18.503333,9.923333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,-0.019296,-0.028667,50.707407,5.038078e+06,59.433333,8.374074,14.014815,1.637037,14.344444,9.685185
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,-0.051185,-0.078519,49.788889,5.095491e+06,59.274074,9.174074,15.714815,1.670370,11.785185,9.403704
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,-0.060258,-0.057806,50.290323,4.763534e+06,60.029032,9.045161,16.738710,1.619355,10.209677,8.654839
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,-0.033944,-0.008944,50.108333,4.356286e+06,60.475000,8.341667,17.030556,1.588889,10.311111,8.219444
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,-0.094500,-0.082714,47.725000,5.055135e+06,60.146429,7.667857,17.400000,1.600000,10.825000,8.160714
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,-0.074867,-0.070133,48.260000,4.878406e+06,61.250000,7.643333,15.776667,1.643333,11.423333,7.976667

In [32]:
# Setting y value for grouping
y = 'choles_check_val'

# Grouping by year
AVG_MMR_USA_27 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_27.reset_index()

# Merging with mmr_predictions 
df_27 = pd.merge(df_26, AVG_MMR_USA_27, how='inner', left_on=['year'], right_on=['year'])
df_27.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,all_determs_val,health_stat_fem_val,population,employer,non_group,medicaid,military,uninsured,air_pollution_val,choles_check_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,-0.055208,52.666667,5.119973e+06,61.200000,6.295833,11.237500,1.545833,17.662500,11.887500,76.129167
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,-0.061458,52.266667,4.994359e+06,58.829167,6.262500,11.750000,1.504167,19.566667,11.387500,76.733333
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,-0.019296,52.937037,4.826144e+06,58.933333,6.155556,12.459259,1.596296,18.740741,10.503704,77.162963
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,-0.098208,49.241667,5.287860e+06,58.395833,6.158333,12.500000,1.658333,19.108333,10.429167,75.537500
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,-0.067567,50.263333,4.679635e+06,58.646667,6.656667,12.240000,1.753333,18.503333,9.923333,75.013333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,-0.028667,50.707407,5.038078e+06,59.433333,8.374074,14.014815,1.637037,14.344444,9.685185,76.674074
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,-0.078519,49.788889,5.095491e+06,59.274074,9.174074,15.714815,1.670370,11.785185,9.403704,76.744444
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,-0.057806,50.290323,4.763534e+06,60.029032,9.045161,16.738710,1.619355,10.209677,8.654839,78.083871
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,-0.008944,50.108333,4.356286e+06,60.475000,8.341667,17.030556,1.588889,10.311111,8.219444,77.655556
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,-0.082714,47.725000,5.055135e+06,60.146429,7.667857,17.400000,1.600000,10.825000,8.160714,86.832143
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,-0.070133,48.260000,4.878406e+06,61.250000,7.643333,15.776667,1.643333,11.423333,7.976667,86.410000

In [33]:
# Setting y value for grouping
y = 'drug_deaths_val'

# Grouping by year
AVG_MMR_USA_28 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_28.reset_index()

# Merging with mmr_predictions 
df_28 = pd.merge(df_27, AVG_MMR_USA_28, how='inner', left_on=['year'], right_on=['year'])
df_28.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,health_stat_fem_val,population,employer,non_group,medicaid,military,uninsured,air_pollution_val,choles_check_val,drug_deaths_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,52.666667,5.119973e+06,61.200000,6.295833,11.237500,1.545833,17.662500,11.887500,76.129167,11.087500
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,52.266667,4.994359e+06,58.829167,6.262500,11.750000,1.504167,19.566667,11.387500,76.733333,12.116667
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,52.937037,4.826144e+06,58.933333,6.155556,12.459259,1.596296,18.740741,10.503704,77.162963,12.625926
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,49.241667,5.287860e+06,58.395833,6.158333,12.500000,1.658333,19.108333,10.429167,75.537500,12.500000
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,50.263333,4.679635e+06,58.646667,6.656667,12.240000,1.753333,18.503333,9.923333,75.013333,13.333333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,50.707407,5.038078e+06,59.433333,8.374074,14.014815,1.637037,14.344444,9.685185,76.674074,13.477778
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,49.788889,5.095491e+06,59.274074,9.174074,15.714815,1.670370,11.785185,9.403704,76.744444,14.740741
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,50.290323,4.763534e+06,60.029032,9.045161,16.738710,1.619355,10.209677,8.654839,78.083871,14.467742
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,50.108333,4.356286e+06,60.475000,8.341667,17.030556,1.588889,10.311111,8.219444,77.655556,16.150000
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,47.725000,5.055135e+06,60.146429,7.667857,17.400000,1.600000,10.825000,8.160714,86.832143,18.928571
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,48.260000,4.878406e+06,61.250000,7.643333,15.776667,1.643333,11.423333,7.976667,86.410000,19.920000

In [34]:
# Setting y value for grouping
y = 'immun_child_val'

# Grouping by year
AVG_MMR_USA_29 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_29.reset_index()

# Merging with mmr_predictions 
df_29 = pd.merge(df_28, AVG_MMR_USA_29, how='inner', left_on=['year'], right_on=['year'])
df_29.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,population,employer,non_group,medicaid,military,uninsured,air_pollution_val,choles_check_val,drug_deaths_val,immun_child_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,5.119973e+06,61.200000,6.295833,11.237500,1.545833,17.662500,11.887500,76.129167,11.087500,77.933333
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,4.994359e+06,58.829167,6.262500,11.750000,1.504167,19.566667,11.387500,76.733333,12.116667,89.859167
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,4.826144e+06,58.933333,6.155556,12.459259,1.596296,18.740741,10.503704,77.162963,12.625926,90.419630
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,5.287860e+06,58.395833,6.158333,12.500000,1.658333,19.108333,10.429167,75.537500,12.500000,90.220000
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,4.679635e+06,58.646667,6.656667,12.240000,1.753333,18.503333,9.923333,75.013333,13.333333,68.626667
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,5.038078e+06,59.433333,8.374074,14.014815,1.637037,14.344444,9.685185,76.674074,13.477778,69.759259
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,5.095491e+06,59.274074,9.174074,15.714815,1.670370,11.785185,9.403704,76.744444,14.740741,71.329630
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,4.763534e+06,60.029032,9.045161,16.738710,1.619355,10.209677,8.654839,78.083871,14.467742,72.364516
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,4.356286e+06,60.475000,8.341667,17.030556,1.588889,10.311111,8.219444,77.655556,16.150000,71.572222
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,5.055135e+06,60.146429,7.667857,17.400000,1.600000,10.825000,8.160714,86.832143,18.928571,70.714286
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,4.878406e+06,61.250000,7.643333,15.776667,1.643333,11.423333,7.976667,86.410000,19.920000,70.026667

In [35]:
# Setting y value for grouping
y = 'infect_dis_val'

# Grouping by year
AVG_MMR_USA_30 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_30.reset_index()

# Merging with mmr_predictions 
df_30 = pd.merge(df_29, AVG_MMR_USA_30, how='inner', left_on=['year'], right_on=['year'])
df_30.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,employer,non_group,medicaid,military,uninsured,air_pollution_val,choles_check_val,drug_deaths_val,immun_child_val,infect_dis_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,61.200000,6.295833,11.237500,1.545833,17.662500,11.887500,76.129167,11.087500,77.933333,18.129167
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,58.829167,6.262500,11.750000,1.504167,19.566667,11.387500,76.733333,12.116667,89.859167,15.825000
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,58.933333,6.155556,12.459259,1.596296,18.740741,10.503704,77.162963,12.625926,90.419630,9.940741
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,58.395833,6.158333,12.500000,1.658333,19.108333,10.429167,75.537500,12.500000,90.220000,12.616667
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,58.646667,6.656667,12.240000,1.753333,18.503333,9.923333,75.013333,13.333333,68.626667,0.033623
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,59.433333,8.374074,14.014815,1.637037,14.344444,9.685185,76.674074,13.477778,69.759259,0.069259
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,59.274074,9.174074,15.714815,1.670370,11.785185,9.403704,76.744444,14.740741,71.329630,0.052926
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,60.029032,9.045161,16.738710,1.619355,10.209677,8.654839,78.083871,14.467742,72.364516,0.013968
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,60.475000,8.341667,17.030556,1.588889,10.311111,8.219444,77.655556,16.150000,71.572222,-0.002278
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,60.146429,7.667857,17.400000,1.600000,10.825000,8.160714,86.832143,18.928571,70.714286,0.051857
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,61.250000,7.643333,15.776667,1.643333,11.423333,7.976667,86.410000,19.920000,70.026667,0.085067

In [36]:
# Setting y value for grouping
y = 'uninsured_val'

# Grouping by year
AVG_MMR_USA_31 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_31.reset_index()

# Merging with mmr_predictions 
df_31 = pd.merge(df_30, AVG_MMR_USA_31, how='inner', left_on=['year'], right_on=['year'])
df_31.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,non_group,medicaid,military,uninsured,air_pollution_val,choles_check_val,drug_deaths_val,immun_child_val,infect_dis_val,uninsured_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,6.295833,11.237500,1.545833,17.662500,11.887500,76.129167,11.087500,77.933333,18.129167,14.433333
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,6.262500,11.750000,1.504167,19.566667,11.387500,76.733333,12.116667,89.859167,15.825000,15.675000
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,6.155556,12.459259,1.596296,18.740741,10.503704,77.162963,12.625926,90.419630,9.940741,15.866667
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,6.158333,12.500000,1.658333,19.108333,10.429167,75.537500,12.500000,90.220000,12.616667,16.033333
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,6.656667,12.240000,1.753333,18.503333,9.923333,75.013333,13.333333,68.626667,0.033623,15.063333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,8.374074,14.014815,1.637037,14.344444,9.685185,76.674074,13.477778,69.759259,0.069259,14.059259
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,9.174074,15.714815,1.670370,11.785185,9.403704,76.744444,14.740741,71.329630,0.052926,13.014815
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,9.045161,16.738710,1.619355,10.209677,8.654839,78.083871,14.467742,72.364516,0.013968,10.054839
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,8.341667,17.030556,1.588889,10.311111,8.219444,77.655556,16.150000,71.572222,-0.002278,8.641667
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,7.667857,17.400000,1.600000,10.825000,8.160714,86.832143,18.928571,70.714286,0.051857,8.450000
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,7.643333,15.776667,1.643333,11.423333,7.976667,86.410000,19.920000,70.026667,0.085067,8.743333

In [37]:
# Setting y value for grouping
y = 'teen_birth_val'

# Grouping by year
AVG_MMR_USA_32 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_32.reset_index()

# Merging with mmr_predictions 
df_32 = pd.merge(df_31, AVG_MMR_USA_32, how='inner', left_on=['year'], right_on=['year'])
df_32.reset_index()

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,medicaid,military,uninsured,air_pollution_val,choles_check_val,drug_deaths_val,immun_child_val,infect_dis_val,uninsured_val,teen_birth_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,11.237500,1.545833,17.662500,11.887500,76.129167,11.087500,77.933333,18.129167,14.433333,43.216667
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,11.750000,1.504167,19.566667,11.387500,76.733333,12.116667,89.859167,15.825000,15.675000,45.608333
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,12.459259,1.596296,18.740741,10.503704,77.162963,12.625926,90.419630,9.940741,15.866667,43.188889
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,12.500000,1.658333,19.108333,10.429167,75.537500,12.500000,90.220000,12.616667,16.033333,36.416667
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,12.240000,1.753333,18.503333,9.923333,75.013333,13.333333,68.626667,0.033623,15.063333,32.903333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,14.014815,1.637037,14.344444,9.685185,76.674074,13.477778,69.759259,0.069259,14.059259,29.777778
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,15.714815,1.670370,11.785185,9.403704,76.744444,14.740741,71.329630,0.052926,13.014815,28.133333
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,16.738710,1.619355,10.209677,8.654839,78.083871,14.467742,72.364516,0.013968,10.054839,25.354839
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,17.030556,1.588889,10.311111,8.219444,77.655556,16.150000,71.572222,-0.002278,8.641667,23.163889
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,17.400000,1.600000,10.825000,8.160714,86.832143,18.928571,70.714286,0.051857,8.450000,22.207143
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,15.776667,1.643333,11.423333,7.976667,86.410000,19.920000,70.026667,0.085067,8.743333,20.403333

In [39]:
# Setting y value for grouping
y = 'primary_care_val'

# Grouping by year
AVG_MMR_USA_33 = mmr_without_race.groupby('year').mean()[y]
AVG_MMR_USA_33.reset_index()

# Merging with mmr_predictions 
df_33 = pd.merge(df_32, AVG_MMR_USA_33, how='inner', left_on=['year'], right_on=['year'])
Combined_AVG_df = df_33.reset_index()
Combined_AVG_df

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,military,uninsured,air_pollution_val,choles_check_val,drug_deaths_val,immun_child_val,infect_dis_val,uninsured_val,teen_birth_val,primary_care_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,1.545833,17.662500,11.887500,76.129167,11.087500,77.933333,18.129167,14.433333,43.216667,117.887500
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,1.504167,19.566667,11.387500,76.733333,12.116667,89.859167,15.825000,15.675000,45.608333,113.012500
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,1.596296,18.740741,10.503704,77.162963,12.625926,90.419630,9.940741,15.866667,43.188889,119.166667
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,1.658333,19.108333,10.429167,75.537500,12.500000,90.220000,12.616667,16.033333,36.416667,116.883333
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,1.753333,18.503333,9.923333,75.013333,13.333333,68.626667,0.033623,15.063333,32.903333,116.733333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,1.637037,14.344444,9.685185,76.674074,13.477778,69.759259,0.069259,14.059259,29.777778,119.737037
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,1.670370,11.785185,9.403704,76.744444,14.740741,71.329630,0.052926,13.014815,28.133333,120.929630
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,1.619355,10.209677,8.654839,78.083871,14.467742,72.364516,0.013968,10.054839,25.354839,143.522581
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,1.588889,10.311111,8.219444,77.655556,16.150000,71.572222,-0.002278,8.641667,23.163889,146.550000
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,1.600000,10.825000,8.160714,86.832143,18.928571,70.714286,0.051857,8.450000,22.207143,153.353571
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,1.643333,11.423333,7.976667,86.410000,19.920000,70.026667,0.085067,8.743333,20.403333,149.673333

In [40]:
Combined_AVG_df.count()

year                        11
maternal_mortality_ratio    11
diabetes_val                11
prem_death_val              11
phys_inac_val               11
low_birthweight_val         11
obesity_val                 11
cardio_death_val            11
medicare                    11
cancer_death_val            11
chlamydia_val               11
child_pov_val               11
smoking_val                 11
infant_mort_val             11
income_ineq_val             11
dentists_val                11
prem_death_ri_val           11
dent_vis_val                11
all_outcomes_val            11
all_determs_val             11
health_stat_fem_val         11
population                  11
employer                    11
non_group                   11
medicaid                    11
military                    11
uninsured                   11
air_pollution_val           11
choles_check_val            11
drug_deaths_val             11
immun_child_val             11
infect_dis_val              11
uninsured_val               11
teen_birth_val              11
primary_care_val            11
dtype: int64

In [41]:
Combined_AVG_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year                      11 non-null     int64
 1   maternal_mortality_ratio  11 non-null     float64
 2   diabetes_val              11 non-null     float64
 3   prem_death_val            11 non-null     float64
 4   phys_inac_val             11 non-null     float64
 5   low_birthweight_val       11 non-null     float64
 6   obesity_val               11 non-null     float64
 7   cardio_death_val          11 non-null     float64
 8   medicare                  11 non-null     float64
 9   cancer_death_val          11 non-null     float64
 10  chlamydia_val             11 non-null     float64
 11  child_pov_val             11 non-null     float64
 12  smoking_val               11 non-null     float64
 13  infant_mort_val           11 non-null     float64
 14  income_ineq_val           11 non-null     float64
 15  dentists_val              11 non-null     float64
 16  prem_death_ri_val         11 non-null     float64
 17  dent_vis_val              11 non-null     float64
 18  all_outcomes_val          11 non-null     float64
 19  all_determs_val           11 non-null     float64
 20  health_stat_fem_val       11 non-null     float64
 21  population                11 non-null     float64
 22  employer                  11 non-null     float64
 23  non_group                 11 non-null     float64
 24  medicaid                  11 non-null     float64
 25  military                  11 non-null     float64
 26  uninsured                 11 non-null     float64
 27  air_pollution_val         11 non-null     float64
 28  choles_check_val          11 non-null     float64
 29  drug_deaths_val           11 non-null     float64
 30  immun_child_val           11 non-null     float64
 31  infect_dis_val            11 non-null     float64
 32  uninsured_val             11 non-null     float64
 33  teen_birth_val            11 non-null     float64
 34  primary_care_val          11 non-null     float64
dtypes: float64(34), int64(1)
memory usage: 3.1 KB

### Saving Final DataFrame to CSV

In [42]:
# Saving merged dataframe into a csv file
Combined_AVG_df.to_csv("../Resources/combined_avg_2009_2019.csv", index=False, header=True, float_format='%.2f')

***
### Performing Time-Series Forecast of Average Annual predictions of all other variables in USA (2020-2030)
***

#### Simple Time-Series Forecast of Average Annual Maternal Mortality in USA

In [43]:
# Importing ML linear regression dependency
from sklearn.linear_model import LinearRegression

# Selecting and assigning the X and y values
X1 = AVG_MMR_USA.reset_index().year.values.reshape(-1,1)
y1 = AVG_MMR_USA.reset_index()['maternal_mortality_ratio'].values

# Steps 1 & 2: Creating and Fitting our model to the data
reg_model = LinearRegression().fit(X1, y1)

# Obtaining the coefficient of determination (R2)
r_square = reg_model.score(X1, y1)

# Setting predictions dictionary to hold variables
predictions=[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values=reg_model.predict(np.array([i]).reshape(1, -1))
    predictions.append(y_values[0])

# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold mmmr values with 10 years predictions
mmr_predict_df = pd.DataFrame(list(zip(years, predictions)), 
               columns =['year', 'maternal_mortality_ratio']) 


# DataFrame with the future predictions
mmr_predict_df

    year  maternal_mortality_ratio
0   2020                 35.963605
1   2021                 36.782910
2   2022                 37.602216
3   2023                 38.421521
4   2024                 39.240827
5   2025                 40.060132
6   2026                 40.879438
7   2027                 41.698743
8   2028                 42.518049
9   2029                 43.337354
10  2030                 44.156659

In [44]:
# Selecting y value
y = 'diabetes_val'
# Grouping by year
AVG_MMR_USA_diabetes = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X2 = AVG_MMR_USA_diabetes.reset_index().year.values.reshape(-1,1)
y2 = AVG_MMR_USA_diabetes.reset_index()['diabetes_val'].values

# Creating and Fitting our model to the data
model2 = LinearRegression().fit(X2, y2)
r_sq_2 = model2.score(X2, y2)
# print(r_sq_2)

# Setting predictions dictionary to hold variables
diabetes=[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model2.predict(np.array([i]).reshape(1, -1))
    diabetes.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions2 = pd.DataFrame(list(zip(years, diabetes)), 
               columns =['year', 'diabetes_val']) 

# DataFrame with the future predictions
predictions2

# Merging with mmr_predictions 
combined1 = pd.merge(mmr_predict_df, predictions2, how='inner', left_on=['year'], right_on=['year'])
combined1

    year  maternal_mortality_ratio  diabetes_val
0   2020                 35.963605     11.875629
1   2021                 36.782910     12.138134
2   2022                 37.602216     12.400638
3   2023                 38.421521     12.663142
4   2024                 39.240827     12.925646
5   2025                 40.060132     13.188151
6   2026                 40.879438     13.450655
7   2027                 41.698743     13.713159
8   2028                 42.518049     13.975663
9   2029                 43.337354     14.238168
10  2030                 44.156659     14.500672

In [45]:
# Selecting y value
y = 'prem_death_val'
# Grouping by year
AVG_MMR_USA_prem = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X3 = AVG_MMR_USA_prem.reset_index().year.values.reshape(-1,1)
y3 = AVG_MMR_USA_prem.reset_index()['prem_death_val'].values

# Creating and Fitting our model to the data
model3 = LinearRegression().fit(X3, y3)
r_sq_3 = model3.score(X3, y3)
# print(r_sq_3)

# Setting predictions dictionary to hold variables
premature =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model3.predict(np.array([i]).reshape(1, -1))
    premature.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions3 = pd.DataFrame(list(zip(years, premature)), 
               columns =['year', 'prem_death_val']) 

# DataFrame with the future predictions
predictions3

# Merging with mmr_predictions 
combined2 = pd.merge(combined1, predictions3, how='inner', left_on=['year'], right_on=['year'])
combined2

    year  maternal_mortality_ratio  diabetes_val  prem_death_val
0   2020                 35.963605     11.875629     7870.161716
1   2021                 36.782910     12.138134     7889.917107
2   2022                 37.602216     12.400638     7909.672499
3   2023                 38.421521     12.663142     7929.427890
4   2024                 39.240827     12.925646     7949.183281
5   2025                 40.060132     13.188151     7968.938673
6   2026                 40.879438     13.450655     7988.694064
7   2027                 41.698743     13.713159     8008.449455
8   2028                 42.518049     13.975663     8028.204847
9   2029                 43.337354     14.238168     8047.960238
10  2030                 44.156659     14.500672     8067.715629

In [46]:
# Selecting y value
y = 'phys_inac_val'
# Grouping by year
AVG_MMR_USA_phys = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X4 = AVG_MMR_USA_phys.reset_index().year.values.reshape(-1,1)
y4 = AVG_MMR_USA_phys.reset_index()['phys_inac_val'].values

# Creating and Fitting our model to the data
model4 = LinearRegression().fit(X4, y4)
r_sq_4 = model4.score(X4, y4)
# print(r_sq_4)

# Setting predictions dictionary to hold variables
physical_inactivity =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model4.predict(np.array([i]).reshape(1, -1))
    physical_inactivity.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions4 = pd.DataFrame(list(zip(years, physical_inactivity)), 
               columns =['year', 'phys_inac_val']) 

# DataFrame with the future predictions
predictions4

# Merging with mmr_predictions 
combined3 = pd.merge(combined2, predictions4, how='inner', left_on=['year'], right_on=['year'])
combined3

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val
0,2020,35.963605,11.875629,7870.161716,26.032977
1,2021,36.782910,12.138134,7889.917107,26.092960
2,2022,37.602216,12.400638,7909.672499,26.152944
3,2023,38.421521,12.663142,7929.427890,26.212928
4,2024,39.240827,12.925646,7949.183281,26.272911
5,2025,40.060132,13.188151,7968.938673,26.332895
6,2026,40.879438,13.450655,7988.694064,26.392878
7,2027,41.698743,13.713159,8008.449455,26.452862
8,2028,42.518049,13.975663,8028.204847,26.512846
9,2029,43.337354,14.238168,8047.960238,26.572829
10,2030,44.156659,14.500672,8067.715629,26.632813

In [47]:
# Selecting y value
y = 'low_birthweight_val'
# Grouping by year
AVG_MMR_USA_lbw = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X5= AVG_MMR_USA_lbw.reset_index().year.values.reshape(-1,1)
y5 = AVG_MMR_USA_lbw.reset_index()['low_birthweight_val'].values

# Creating and Fitting our model to the data
model5 = LinearRegression().fit(X5, y5)
r_sq_5 = model5.score(X5, y5)
# print(r_sq_5)

# Setting predictions dictionary to hold variables
low_birthweight =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model5.predict(np.array([i]).reshape(1, -1))
    low_birthweight.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions5 = pd.DataFrame(list(zip(years, low_birthweight)), 
               columns =['year', 'low_birthweight_val']) 

# DataFrame with the future predictions
predictions5

# Merging with mmr_predictions 
combined4 = pd.merge(combined3, predictions5, how='inner', left_on=['year'], right_on=['year'])
combined4

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221

In [48]:
# Selecting y value
y = 'obesity_val'
# Grouping by year
AVG_MMR_USA_ob = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X6 = AVG_MMR_USA_ob.reset_index().year.values.reshape(-1,1)
y6 = AVG_MMR_USA_ob.reset_index()['obesity_val'].values

# Creating and Fitting our model to the data
model6 = LinearRegression().fit(X6, y6)
r_sq_6 = model6.score(X6, y6)
# print(r_sq_6)

# Setting predictions dictionary to hold variables
obesity_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model6.predict(np.array([i]).reshape(1, -1))
    obesity_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions6 = pd.DataFrame(list(zip(years, obesity_val)), 
               columns =['year', 'obesity_val']) 

# DataFrame with the future predictions
predictions6

# Merging with mmr_predictions 
combined5 = pd.merge(combined4, predictions6, how='inner', left_on=['year'], right_on=['year'])
combined5

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484

In [49]:
# Selecting y value
y = 'cardio_death_val'
# Grouping by year
AVG_MMR_USA_cd = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X7 = AVG_MMR_USA_cd.reset_index().year.values.reshape(-1,1)
y7 = AVG_MMR_USA_cd.reset_index()['cardio_death_val'].values

# Creating and Fitting our model to the data
model7 = LinearRegression().fit(X7, y7)
r_sq_7 = model7.score(X7, y7)
# print(r_sq_7)

# Setting predictions dictionary to hold variables
cardio_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model7.predict(np.array([i]).reshape(1, -1))
    cardio_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions7 = pd.DataFrame(list(zip(years, cardio_val)), 
               columns =['year', 'cardio_death_val']) 

# DataFrame with the future predictions
predictions7

# Merging with mmr_predictions 
combined6 = pd.merge(combined5, predictions7, how='inner', left_on=['year'], right_on=['year'])
combined6

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279

In [50]:
# Selecting y value
y = 'medicare'
# Grouping by year
AVG_MMR_USA_med = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X8 = AVG_MMR_USA_med.reset_index().year.values.reshape(-1,1)
y8 = AVG_MMR_USA_med.reset_index()['medicare'].values

# Creating and Fitting our model to the data
model8 = LinearRegression().fit(X8, y8)
r_sq_8 = model8.score(X8, y8)
# print(r_sq_8)

# Setting predictions dictionary to hold variables
medicare =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model8.predict(np.array([i]).reshape(1, -1))
    medicare.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions8 = pd.DataFrame(list(zip(years, medicare)), 
               columns =['year', 'medicare']) 

# DataFrame with the future predictions
predictions8

# Merging with mmr_predictions 
combined7 = pd.merge(combined6, predictions8, how='inner', left_on=['year'], right_on=['year'])
combined7

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480

In [51]:
# Selecting y value
y = 'cancer_death_val'
# Grouping by year
AVG_MMR_USA_cancer = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X9 = AVG_MMR_USA_cancer.reset_index().year.values.reshape(-1,1)
y9 = AVG_MMR_USA_cancer.reset_index()['cancer_death_val'].values

# Creating and Fitting our model to the data
model9 = LinearRegression().fit(X9, y9)
r_sq_9 = model9.score(X9, y9)
# print(r_sq_9)

# Setting predictions dictionary to hold variables
cancer_death_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model9.predict(np.array([i]).reshape(1, -1))
    cancer_death_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions9 = pd.DataFrame(list(zip(years, cancer_death_val)), 
               columns =['year', 'cancer_death_val']) 

# DataFrame with the future predictions
predictions9

# Merging with mmr_predictions 
combined8 = pd.merge(combined7, predictions9, how='inner', left_on=['year'], right_on=['year'])
combined8

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254

In [52]:
# Selecting y value
y = 'chlamydia_val'
# Grouping by year
AVG_MMR_USA_chlamydia = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X10 = AVG_MMR_USA_chlamydia.reset_index().year.values.reshape(-1,1)
y10 = AVG_MMR_USA_chlamydia.reset_index()['chlamydia_val'].values

# Creating and Fitting our model to the data
model10 = LinearRegression().fit(X10, y10)
r_sq_10 = model10.score(X10, y10)
# print(r_sq_10)

# Setting predictions dictionary to hold variables
chlamydia_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model10.predict(np.array([i]).reshape(1, -1))
    chlamydia_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions10 = pd.DataFrame(list(zip(years, chlamydia_val)), 
               columns =['year', 'chlamydia_val']) 

# DataFrame with the future predictions
predictions10

# Merging with mmr_predictions 
combined9 = pd.merge(combined8, predictions10, how='inner', left_on=['year'], right_on=['year'])
combined9

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117

In [53]:
# Selecting y value
y = 'child_pov_val'
# Grouping by year
AVG_MMR_USA_child = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X11 = AVG_MMR_USA_child.reset_index().year.values.reshape(-1,1)
y11 = AVG_MMR_USA_child.reset_index()['child_pov_val'].values

# Creating and Fitting our model to the data
model11 = LinearRegression().fit(X11, y11)
r_sq_11 = model11.score(X11, y11)
# print(r_sq_11)

# Setting predictions dictionary to hold variables
child_pov_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model11.predict(np.array([i]).reshape(1, -1))
    child_pov_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions11 = pd.DataFrame(list(zip(years, child_pov_val)), 
               columns =['year', 'child_pov_val']) 

# DataFrame with the future predictions
predictions11

# Merging with mmr_predictions 
combined10 = pd.merge(combined9, predictions11, how='inner', left_on=['year'], right_on=['year'])
combined10

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634,19.117183
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582,18.955433
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531,18.793683
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479,18.631933
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427,18.470183
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375,18.308433
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324,18.146682
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272,17.984932
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220,17.823182
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168,17.661432
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117,17.499682

In [54]:
# Selecting y value
y = 'smoking_val'
# Grouping by year
AVG_MMR_USA_smoking = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X12 = AVG_MMR_USA_smoking.reset_index().year.values.reshape(-1,1)
y12 = AVG_MMR_USA_smoking.reset_index()['smoking_val'].values

# Creating and Fitting our model to the data
model12 = LinearRegression().fit(X12, y12)
r_sq_12 = model12.score(X12, y12)
# print(r_sq_12)

# Setting predictions dictionary to hold variables
smoking_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model12.predict(np.array([i]).reshape(1, -1))
    smoking_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions12 = pd.DataFrame(list(zip(years, smoking_val)), 
               columns =['year', 'smoking_val']) 

# DataFrame with the future predictions
predictions12

# Merging with mmr_predictions 
combined11 = pd.merge(combined10, predictions12, how='inner', left_on=['year'], right_on=['year'])
combined11

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634,19.117183,17.271319
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582,18.955433,17.010809
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531,18.793683,16.750299
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479,18.631933,16.489790
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427,18.470183,16.229280
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375,18.308433,15.968771
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324,18.146682,15.708261
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272,17.984932,15.447752
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220,17.823182,15.187242
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168,17.661432,14.926732
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117,17.499682,14.666223

In [55]:
# Selecting y value
y = 'infant_mort_val'
# Grouping by year
AVG_MMR_USA_infant = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X13 = AVG_MMR_USA_infant.reset_index().year.values.reshape(-1,1)
y13 = AVG_MMR_USA_infant.reset_index()['infant_mort_val'].values

# Creating and Fitting our model to the data
model13 = LinearRegression().fit(X13, y13)
r_sq_13 = model13.score(X13, y13)
# print(r_sq_13)

# Setting predictions dictionary to hold variables
infant_mort_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model13.predict(np.array([i]).reshape(1, -1))
    infant_mort_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions13 = pd.DataFrame(list(zip(years, infant_mort_val)), 
               columns =['year', 'infant_mort_val']) 

# DataFrame with the future predictions
predictions13

# Merging with mmr_predictions 
combined12 = pd.merge(combined11, predictions13, how='inner', left_on=['year'], right_on=['year'])
combined12

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634,19.117183,17.271319,5.992582
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582,18.955433,17.010809,5.897575
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531,18.793683,16.750299,5.802567
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479,18.631933,16.489790,5.707559
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427,18.470183,16.229280,5.612552
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375,18.308433,15.968771,5.517544
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324,18.146682,15.708261,5.422537
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272,17.984932,15.447752,5.327529
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220,17.823182,15.187242,5.232522
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168,17.661432,14.926732,5.137514
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117,17.499682,14.666223,5.042506

In [56]:
# Selecting y value
y = 'income_ineq_val'
# Grouping by year
AVG_MMR_USA_income = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X14 = AVG_MMR_USA_income.reset_index().year.values.reshape(-1,1)
y14 = AVG_MMR_USA_income.reset_index()['income_ineq_val'].values

# Creating and Fitting our model to the data
model14 = LinearRegression().fit(X14, y14)
r_sq_14 = model14.score(X14, y14)
# print(r_sq_14)

# Setting predictions dictionary to hold variables
income_ineq_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model14.predict(np.array([i]).reshape(1, -1))
    income_ineq_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions14 = pd.DataFrame(list(zip(years, income_ineq_val)), 
               columns =['year', 'income_ineq_val']) 

# DataFrame with the future predictions
predictions14

# Merging with mmr_predictions 
combined13 = pd.merge(combined12, predictions14, how='inner', left_on=['year'], right_on=['year'])
combined13

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634,19.117183,17.271319,5.992582,4.869784
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582,18.955433,17.010809,5.897575,4.889125
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531,18.793683,16.750299,5.802567,4.908465
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479,18.631933,16.489790,5.707559,4.927806
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427,18.470183,16.229280,5.612552,4.947146
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375,18.308433,15.968771,5.517544,4.966487
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324,18.146682,15.708261,5.422537,4.985828
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272,17.984932,15.447752,5.327529,5.005168
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220,17.823182,15.187242,5.232522,5.024509
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168,17.661432,14.926732,5.137514,5.043849
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117,17.499682,14.666223,5.042506,5.063190

In [57]:
# Selecting y value
y = 'dentists_val'
# Grouping by year
AVG_MMR_USA_dentist = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X15 = AVG_MMR_USA_dentist.reset_index().year.values.reshape(-1,1)
y15 = AVG_MMR_USA_dentist.reset_index()['dentists_val'].values

# Creating and Fitting our model to the data
model15 = LinearRegression().fit(X15, y15)
r_sq_15 = model15.score(X15, y15)
# print(r_sq_15)

# Setting predictions dictionary to hold variables
dentists_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model15.predict(np.array([i]).reshape(1, -1))
    dentists_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions15 = pd.DataFrame(list(zip(years, dentists_val)), 
               columns =['year', 'dentists_val']) 

# DataFrame with the future predictions
predictions15

# Merging with mmr_predictions 
combined14 = pd.merge(combined13, predictions15, how='inner', left_on=['year'], right_on=['year'])
combined14

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634,19.117183,17.271319,5.992582,4.869784,58.066430
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582,18.955433,17.010809,5.897575,4.889125,58.298061
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531,18.793683,16.750299,5.802567,4.908465,58.529693
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479,18.631933,16.489790,5.707559,4.927806,58.761324
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427,18.470183,16.229280,5.612552,4.947146,58.992956
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375,18.308433,15.968771,5.517544,4.966487,59.224587
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324,18.146682,15.708261,5.422537,4.985828,59.456219
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272,17.984932,15.447752,5.327529,5.005168,59.687850
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220,17.823182,15.187242,5.232522,5.024509,59.919482
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168,17.661432,14.926732,5.137514,5.043849,60.151113
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117,17.499682,14.666223,5.042506,5.063190,60.382745

In [58]:
# Selecting y value
y = 'prem_death_ri_val'
# Grouping by year
AVG_MMR_USA_prem = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X16 = AVG_MMR_USA_prem.reset_index().year.values.reshape(-1,1)
y16 = AVG_MMR_USA_prem.reset_index()['prem_death_ri_val'].values

# Creating and Fitting our model to the data
model16 = LinearRegression().fit(X16, y16)
r_sq_16 = model16.score(X16, y16)
# print(r_sq_16)

# Setting predictions dictionary to hold variables
prem_death_ri_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model16.predict(np.array([i]).reshape(1, -1))
    prem_death_ri_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions16 = pd.DataFrame(list(zip(years, prem_death_ri_val)), 
               columns =['year', 'prem_death_ri_val']) 

# DataFrame with the future predictions
predictions16

# Merging with mmr_predictions 
combined15 = pd.merge(combined14, predictions16, how='inner', left_on=['year'], right_on=['year'])
combined15

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634,19.117183,17.271319,5.992582,4.869784,58.066430,1.402815
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582,18.955433,17.010809,5.897575,4.889125,58.298061,1.389186
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531,18.793683,16.750299,5.802567,4.908465,58.529693,1.375557
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479,18.631933,16.489790,5.707559,4.927806,58.761324,1.361929
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427,18.470183,16.229280,5.612552,4.947146,58.992956,1.348300
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375,18.308433,15.968771,5.517544,4.966487,59.224587,1.334672
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324,18.146682,15.708261,5.422537,4.985828,59.456219,1.321043
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272,17.984932,15.447752,5.327529,5.005168,59.687850,1.307415
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220,17.823182,15.187242,5.232522,5.024509,59.919482,1.293786
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168,17.661432,14.926732,5.137514,5.043849,60.151113,1.280157
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117,17.499682,14.666223,5.042506,5.063190,60.382745,1.266529

In [59]:
# Selecting y value
y = 'dent_vis_val'
# Grouping by year
AVG_MMR_USA_dent = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X17 = AVG_MMR_USA_dent.reset_index().year.values.reshape(-1,1)
y17 = AVG_MMR_USA_dent.reset_index()['dent_vis_val'].values

# Creating and Fitting our model to the data
model17 = LinearRegression().fit(X17, y17)
r_sq_17 = model17.score(X17, y17)
# print(r_sq_17)

# Setting predictions dictionary to hold variables
dent_vis_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model17.predict(np.array([i]).reshape(1, -1))
    dent_vis_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions17 = pd.DataFrame(list(zip(years, dent_vis_val)), 
               columns =['year', 'dent_vis_val']) 

# DataFrame with the future predictions
predictions17

# Merging with mmr_predictions 
combined16 = pd.merge(combined15, predictions17, how='inner', left_on=['year'], right_on=['year'])
combined16

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634,19.117183,17.271319,5.992582,4.869784,58.066430,1.402815,62.919180
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582,18.955433,17.010809,5.897575,4.889125,58.298061,1.389186,62.357449
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531,18.793683,16.750299,5.802567,4.908465,58.529693,1.375557,61.795719
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479,18.631933,16.489790,5.707559,4.927806,58.761324,1.361929,61.233988
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427,18.470183,16.229280,5.612552,4.947146,58.992956,1.348300,60.672258
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375,18.308433,15.968771,5.517544,4.966487,59.224587,1.334672,60.110527
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324,18.146682,15.708261,5.422537,4.985828,59.456219,1.321043,59.548796
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272,17.984932,15.447752,5.327529,5.005168,59.687850,1.307415,58.987066
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220,17.823182,15.187242,5.232522,5.024509,59.919482,1.293786,58.425335
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168,17.661432,14.926732,5.137514,5.043849,60.151113,1.280157,57.863605
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117,17.499682,14.666223,5.042506,5.063190,60.382745,1.266529,57.301874

In [60]:
# Selecting y value
y = 'all_outcomes_val'
# Grouping by year
AVG_MMR_USA_outcomes = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X18 = AVG_MMR_USA_outcomes.reset_index().year.values.reshape(-1,1)
y18 = AVG_MMR_USA_outcomes.reset_index()['all_outcomes_val'].values

# Creating and Fitting our model to the data
model18 = LinearRegression().fit(X18, y18)
r_sq_18 = model18.score(X18, y18)
# print(r_sq_18)

# Setting predictions dictionary to hold variables
all_outcomes_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model18.predict(np.array([i]).reshape(1, -1))
    all_outcomes_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions18 = pd.DataFrame(list(zip(years, all_outcomes_val)), 
               columns =['year', 'all_outcomes_val']) 

# DataFrame with the future predictions
predictions18

# Merging with mmr_predictions 
combined17 = pd.merge(combined16, predictions18, how='inner', left_on=['year'], right_on=['year'])
combined17

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634,19.117183,17.271319,5.992582,4.869784,58.066430,1.402815,62.919180,-0.092330
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582,18.955433,17.010809,5.897575,4.889125,58.298061,1.389186,62.357449,-0.101984
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531,18.793683,16.750299,5.802567,4.908465,58.529693,1.375557,61.795719,-0.111639
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479,18.631933,16.489790,5.707559,4.927806,58.761324,1.361929,61.233988,-0.121293
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427,18.470183,16.229280,5.612552,4.947146,58.992956,1.348300,60.672258,-0.130947
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375,18.308433,15.968771,5.517544,4.966487,59.224587,1.334672,60.110527,-0.140601
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324,18.146682,15.708261,5.422537,4.985828,59.456219,1.321043,59.548796,-0.150255
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272,17.984932,15.447752,5.327529,5.005168,59.687850,1.307415,58.987066,-0.159909
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220,17.823182,15.187242,5.232522,5.024509,59.919482,1.293786,58.425335,-0.169563
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168,17.661432,14.926732,5.137514,5.043849,60.151113,1.280157,57.863605,-0.179217
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117,17.499682,14.666223,5.042506,5.063190,60.382745,1.266529,57.301874,-0.188871

In [61]:
# Selecting y value
y = 'all_determs_val'
# Grouping by year
AVG_MMR_USA_determs = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X19 = AVG_MMR_USA_determs.reset_index().year.values.reshape(-1,1)
y19 = AVG_MMR_USA_determs.reset_index()['all_determs_val'].values

# Creating and Fitting our model to the data
model19 = LinearRegression().fit(X19, y19)
r_sq_19 = model19.score(X19, y19)
# print(r_sq_19)

# Setting predictions dictionary to hold variables
all_determs_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model19.predict(np.array([i]).reshape(1, -1))
    all_determs_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions19 = pd.DataFrame(list(zip(years, all_determs_val)), 
               columns =['year', 'all_determs_val']) 

# DataFrame with the future predictions
predictions19

# Merging with mmr_predictions 
combined18 = pd.merge(combined17, predictions19, how='inner', left_on=['year'], right_on=['year'])
combined18

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,chlamydia_val,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,526.793634,19.117183,17.271319,5.992582,4.869784,58.066430,1.402815,62.919180,-0.092330,-0.060342
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,539.215582,18.955433,17.010809,5.897575,4.889125,58.298061,1.389186,62.357449,-0.101984,-0.060876
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,551.637531,18.793683,16.750299,5.802567,4.908465,58.529693,1.375557,61.795719,-0.111639,-0.061410
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,564.059479,18.631933,16.489790,5.707559,4.927806,58.761324,1.361929,61.233988,-0.121293,-0.061944
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,576.481427,18.470183,16.229280,5.612552,4.947146,58.992956,1.348300,60.672258,-0.130947,-0.062478
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,588.903375,18.308433,15.968771,5.517544,4.966487,59.224587,1.334672,60.110527,-0.140601,-0.063012
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,601.325324,18.146682,15.708261,5.422537,4.985828,59.456219,1.321043,59.548796,-0.150255,-0.063546
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,613.747272,17.984932,15.447752,5.327529,5.005168,59.687850,1.307415,58.987066,-0.159909,-0.064080
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,626.169220,17.823182,15.187242,5.232522,5.024509,59.919482,1.293786,58.425335,-0.169563,-0.064615
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,638.591168,17.661432,14.926732,5.137514,5.043849,60.151113,1.280157,57.863605,-0.179217,-0.065149
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,651.013117,17.499682,14.666223,5.042506,5.063190,60.382745,1.266529,57.301874,-0.188871,-0.065683

In [62]:
# Selecting y value
y = 'health_stat_fem_val'
# Grouping by year
AVG_MMR_USA_health = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X20 = AVG_MMR_USA_health.reset_index().year.values.reshape(-1,1)
y20 = AVG_MMR_USA_health.reset_index()['health_stat_fem_val'].values

# Creating and Fitting our model to the data
model20 = LinearRegression().fit(X20, y20)
r_sq_20 = model20.score(X20, y20)
# print(r_sq_20)

# Setting predictions dictionary to hold variables
health_stat_fem_val =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model20.predict(np.array([i]).reshape(1, -1))
    health_stat_fem_val.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions20 = pd.DataFrame(list(zip(years, health_stat_fem_val)), 
               columns =['year', 'health_stat_fem_val']) 

# DataFrame with the future predictions
predictions20

# Merging with mmr_predictions 
combined19 = pd.merge(combined18, predictions20, how='inner', left_on=['year'], right_on=['year'])
combined19

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,...,19.117183,17.271319,5.992582,4.869784,58.066430,1.402815,62.919180,-0.092330,-0.060342,47.819761
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,...,18.955433,17.010809,5.897575,4.889125,58.298061,1.389186,62.357449,-0.101984,-0.060876,47.391914
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,...,18.793683,16.750299,5.802567,4.908465,58.529693,1.375557,61.795719,-0.111639,-0.061410,46.964066
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,...,18.631933,16.489790,5.707559,4.927806,58.761324,1.361929,61.233988,-0.121293,-0.061944,46.536218
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,...,18.470183,16.229280,5.612552,4.947146,58.992956,1.348300,60.672258,-0.130947,-0.062478,46.108371
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,...,18.308433,15.968771,5.517544,4.966487,59.224587,1.334672,60.110527,-0.140601,-0.063012,45.680523
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,...,18.146682,15.708261,5.422537,4.985828,59.456219,1.321043,59.548796,-0.150255,-0.063546,45.252675
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,...,17.984932,15.447752,5.327529,5.005168,59.687850,1.307415,58.987066,-0.159909,-0.064080,44.824828
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,...,17.823182,15.187242,5.232522,5.024509,59.919482,1.293786,58.425335,-0.169563,-0.064615,44.396980
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,...,17.661432,14.926732,5.137514,5.043849,60.151113,1.280157,57.863605,-0.179217,-0.065149,43.969132
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,...,17.499682,14.666223,5.042506,5.063190,60.382745,1.266529,57.301874,-0.188871,-0.065683,43.541285

In [64]:
# Selecting y value
y = 'population'
# Grouping by year
AVG_MMR_USA_population = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X21 = AVG_MMR_USA_population.reset_index().year.values.reshape(-1,1)
y21 = AVG_MMR_USA_population.reset_index()['population'].values

# Creating and Fitting our model to the data
model21 = LinearRegression().fit(X21, y21)
r_sq_21 = model21.score(X21, y21)
# print(r_sq_21)

# Setting predictions dictionary to hold variables
population =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model21.predict(np.array([i]).reshape(1, -1))
    population.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions21 = pd.DataFrame(list(zip(years, population)), 
               columns =['year', 'population']) 

# DataFrame with the future predictions
predictions21

# Merging with mmr_predictions 
combined20 = pd.merge(combined19, predictions21, how='inner', left_on=['year'], right_on=['year'])
combined20

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val,population
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,...,17.271319,5.992582,4.869784,58.066430,1.402815,62.919180,-0.092330,-0.060342,47.819761,4.753695e+06
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,...,17.010809,5.897575,4.889125,58.298061,1.389186,62.357449,-0.101984,-0.060876,47.391914,4.726357e+06
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,...,16.750299,5.802567,4.908465,58.529693,1.375557,61.795719,-0.111639,-0.061410,46.964066,4.699020e+06
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,...,16.489790,5.707559,4.927806,58.761324,1.361929,61.233988,-0.121293,-0.061944,46.536218,4.671683e+06
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,...,16.229280,5.612552,4.947146,58.992956,1.348300,60.672258,-0.130947,-0.062478,46.108371,4.644346e+06
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,...,15.968771,5.517544,4.966487,59.224587,1.334672,60.110527,-0.140601,-0.063012,45.680523,4.617008e+06
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,...,15.708261,5.422537,4.985828,59.456219,1.321043,59.548796,-0.150255,-0.063546,45.252675,4.589671e+06
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,...,15.447752,5.327529,5.005168,59.687850,1.307415,58.987066,-0.159909,-0.064080,44.824828,4.562334e+06
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,...,15.187242,5.232522,5.024509,59.919482,1.293786,58.425335,-0.169563,-0.064615,44.396980,4.534996e+06
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,...,14.926732,5.137514,5.043849,60.151113,1.280157,57.863605,-0.179217,-0.065149,43.969132,4.507659e+06
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,...,14.666223,5.042506,5.063190,60.382745,1.266529,57.301874,-0.188871,-0.065683,43.541285,4.480322e+06

In [66]:
# Selecting y value
y = 'employer'
# Grouping by year
AVG_MMR_USA_employer = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X22 = AVG_MMR_USA_employer.reset_index().year.values.reshape(-1,1)
y22 = AVG_MMR_USA_employer.reset_index()['employer'].values

# Creating and Fitting our model to the data
model22 = LinearRegression().fit(X22, y22)
r_sq_22 = model22.score(X22, y22)
# print(r_sq_22)

# Setting predictions dictionary to hold variables
employer =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model22.predict(np.array([i]).reshape(1, -1))
    employer.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions22 = pd.DataFrame(list(zip(years, employer)), 
               columns =['year', 'employer']) 

# DataFrame with the future predictions
predictions22

# Merging with mmr_predictions 
combined21 = pd.merge(combined20, predictions22, how='inner', left_on=['year'], right_on=['year'])
combined21

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val,population,employer
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,...,5.992582,4.869784,58.066430,1.402815,62.919180,-0.092330,-0.060342,47.819761,4.753695e+06,60.457780
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,...,5.897575,4.889125,58.298061,1.389186,62.357449,-0.101984,-0.060876,47.391914,4.726357e+06,60.585397
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,...,5.802567,4.908465,58.529693,1.375557,61.795719,-0.111639,-0.061410,46.964066,4.699020e+06,60.713014
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,...,5.707559,4.927806,58.761324,1.361929,61.233988,-0.121293,-0.061944,46.536218,4.671683e+06,60.840631
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,...,5.612552,4.947146,58.992956,1.348300,60.672258,-0.130947,-0.062478,46.108371,4.644346e+06,60.968247
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,...,5.517544,4.966487,59.224587,1.334672,60.110527,-0.140601,-0.063012,45.680523,4.617008e+06,61.095864
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,...,5.422537,4.985828,59.456219,1.321043,59.548796,-0.150255,-0.063546,45.252675,4.589671e+06,61.223481
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,...,5.327529,5.005168,59.687850,1.307415,58.987066,-0.159909,-0.064080,44.824828,4.562334e+06,61.351098
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,...,5.232522,5.024509,59.919482,1.293786,58.425335,-0.169563,-0.064615,44.396980,4.534996e+06,61.478715
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,...,5.137514,5.043849,60.151113,1.280157,57.863605,-0.179217,-0.065149,43.969132,4.507659e+06,61.606332
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,...,5.042506,5.063190,60.382745,1.266529,57.301874,-0.188871,-0.065683,43.541285,4.480322e+06,61.733948

In [67]:
# Selecting y value
y = 'non_group'
# Grouping by year
AVG_MMR_USA_non_group = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X23 = AVG_MMR_USA_non_group.reset_index().year.values.reshape(-1,1)
y23 = AVG_MMR_USA_non_group.reset_index()['non_group'].values

# Creating and Fitting our model to the data
model23 = LinearRegression().fit(X23, y23)
r_sq_23 = model22.score(X23, y23)
# print(r_sq_23)

# Setting predictions dictionary to hold variables
non_group =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model23.predict(np.array([i]).reshape(1, -1))
    non_group.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions23 = pd.DataFrame(list(zip(years, non_group)), 
               columns =['year', 'non_group']) 

# DataFrame with the future predictions
predictions23

# Merging with mmr_predictions 
combined22 = pd.merge(combined21, predictions23, how='inner', left_on=['year'], right_on=['year'])
combined22

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val,population,employer,non_group
0,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,...,4.869784,58.066430,1.402815,62.919180,-0.092330,-0.060342,47.819761,4.753695e+06,60.457780,8.918186
1,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,...,4.889125,58.298061,1.389186,62.357449,-0.101984,-0.060876,47.391914,4.726357e+06,60.585397,9.165535
2,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,...,4.908465,58.529693,1.375557,61.795719,-0.111639,-0.061410,46.964066,4.699020e+06,60.713014,9.412883
3,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,...,4.927806,58.761324,1.361929,61.233988,-0.121293,-0.061944,46.536218,4.671683e+06,60.840631,9.660232
4,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,...,4.947146,58.992956,1.348300,60.672258,-0.130947,-0.062478,46.108371,4.644346e+06,60.968247,9.907580
5,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,...,4.966487,59.224587,1.334672,60.110527,-0.140601,-0.063012,45.680523,4.617008e+06,61.095864,10.154928
6,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,...,4.985828,59.456219,1.321043,59.548796,-0.150255,-0.063546,45.252675,4.589671e+06,61.223481,10.402277
7,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,...,5.005168,59.687850,1.307415,58.987066,-0.159909,-0.064080,44.824828,4.562334e+06,61.351098,10.649625
8,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,...,5.024509,59.919482,1.293786,58.425335,-0.169563,-0.064615,44.396980,4.534996e+06,61.478715,10.896974
9,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,...,5.043849,60.151113,1.280157,57.863605,-0.179217,-0.065149,43.969132,4.507659e+06,61.606332,11.144322
10,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,...,5.063190,60.382745,1.266529,57.301874,-0.188871,-0.065683,43.541285,4.480322e+06,61.733948,11.391671

In [ ]:
# Selecting y value
y = 'medicaid'
# Grouping by year
AVG_MMR_USA_medicaid = mmr_without_race.groupby('year').mean()[y]

# Selecting and assigning the X and y values
X23 = AVG_MMR_USA_medicaid.reset_index().year.values.reshape(-1,1)
y23 = AVG_MMR_USA_medicaid.reset_index()['medicaid'].values

# Creating and Fitting our model to the data
model23 = LinearRegression().fit(X23, y23)
r_sq_23 = model22.score(X23, y23)
# print(r_sq_23)

# Setting predictions dictionary to hold variables
medicaid =[]

# Creating a for-loop to return predictions from model
for i in range(2020,2031):
    y_values = model23.predict(np.array([i]).reshape(1, -1))
    medicaid.append(y_values[0])
    
# Creating a year range to hold years values with the future predictions
years = [i for i in range(2020,2031)] 

# Creating a new DataFrame to hold values with 10 years predictions
predictions23 = pd.DataFrame(list(zip(years, medicaid)), 
               columns =['year', 'non_group']) 

# DataFrame with the future predictions
predictions23

# Merging with mmr_predictions 
combined22 = pd.merge(combined21, predictions23, how='inner', left_on=['year'], right_on=['year'])
combined22

In [63]:
combined19.count()

year                        11
maternal_mortality_ratio    11
diabetes_val                11
prem_death_val              11
phys_inac_val               11
low_birthweight_val         11
obesity_val                 11
cardio_death_val            11
medicare                    11
cancer_death_val            11
chlamydia_val               11
child_pov_val               11
smoking_val                 11
infant_mort_val             11
income_ineq_val             11
dentists_val                11
prem_death_ri_val           11
dent_vis_val                11
all_outcomes_val            11
all_determs_val             11
health_stat_fem_val         11
dtype: int64

### Saving Final DataFrame to CSV

In [46]:
# Saving merged dataframe into a csv file
combined19.to_csv("../Resources/combined_avg_2020_2030.csv", index=False, header=True, float_format='%.2f')

***
## Combining Both Annual Average Dataframes 
***
Using Pandas `concat()` function to concatenate the two dataframes along rows

In [57]:
# Combining the two annual average dataframes with pandas `concat()`
USA_Annual_AVG_df = pd.concat([Combined_AVG_df, combined19], ignore_index=True)
USA_Annual_AVG_df

,year,maternal_mortality_ratio,diabetes_val,prem_death_val,phys_inac_val,low_birthweight_val,obesity_val,cardio_death_val,medicare,cancer_death_val,...,child_pov_val,smoking_val,infant_mort_val,income_ineq_val,dentists_val,prem_death_ri_val,dent_vis_val,all_outcomes_val,all_determs_val,health_stat_fem_val
0,2009,26.747083,8.920833,7845.041667,25.879167,8.475000,27.845833,289.720833,2.037500,197.729167,...,18.529167,19.641667,7.254167,4.547917,54.887500,1.604167,69.491667,0.016708,-0.055208,52.666667
1,2010,25.715417,9.291667,7816.875000,25.350000,8.383333,28.670833,280.808333,2.058333,195.583333,...,21.225000,19.166667,7.120833,4.633750,55.062500,1.504167,68.895833,0.012917,-0.061458,52.266667
2,2011,27.871481,9.229630,7603.666667,24.644444,8.303704,28.407407,269.237037,2.085185,194.277778,...,21.255556,18.140741,6.744444,4.691481,56.674074,1.544444,69.488889,0.022185,-0.019296,52.937037
3,2012,29.929583,10.208333,8014.041667,27.183333,8.520833,28.704167,271.795833,2.216667,196.866667,...,21.679167,21.633333,6.816667,4.867083,55.620833,1.495833,68.704167,-0.069458,-0.098208,49.241667
4,2013,31.729333,10.200000,7635.300000,23.720000,8.290000,28.693333,257.976667,2.210000,193.133333,...,21.450000,20.163333,6.460000,4.782000,56.910000,1.500000,64.690000,-0.026767,-0.067567,50.263333
5,2014,32.339259,10.070370,7233.481481,26.818519,8.096296,29.014815,255.055556,2.192593,191.800000,...,18.859259,19.103704,6.266667,4.758148,57.655556,1.503704,65.314815,-0.019296,-0.028667,50.707407
6,2015,31.944074,10.677778,7530.666667,24.177778,8.325926,29.900000,262.066667,2.370370,194.244444,...,21.644444,18.685185,6.385185,4.812963,57.440741,1.414815,63.455556,-0.051185,-0.078519,49.788889
7,2016,35.440968,10.670968,7582.193548,27.041935,8.280645,30.216129,262.293548,2.354839,196.519355,...,19.541935,18.270968,6.274194,4.790323,57.416129,1.429032,64.038710,-0.060258,-0.057806,50.290323
8,2017,34.208889,10.869444,7658.861111,24.272222,8.244444,30.238889,261.152778,2.263889,193.558333,...,17.900000,17.386111,6.097222,4.777222,57.925000,1.433333,65.522222,-0.033944,-0.008944,50.108333
9,2018,31.526071,11.514286,8270.428571,28.246429,8.592857,31.832143,273.446429,2.364286,199.325000,...,20.500000,18.246429,6.442857,4.883929,56.960714,1.414286,64.200000,-0.094500,-0.082714,47.725000
10,2019,34.073333,11.653333,8077.366667,25.070000,8.600000,32.166667,273.310000,2.263333,195.203333,...,18.380000,16.740000,6.326667,4.746333,56.890000,1.486667,65.383333,-0.074867,-0.070133,48.260000
11,2020,35.963605,11.875629,7870.161716,26.032977,8.419778,32.006807,260.587473,2.401134,195.327103,...,19.117183,17.271319,5.992582,4.869784,58.066430,1.402815,62.919180,-0.092330,-0.060342,47.819761
12,2021,36.782910,12.138134,7889.917107,26.092960,8.427422,32.406575,259.217753,2.431369,195.332518,...,18.955433,17.010809,5.897575,4.889125,58.298061,1.389186,62.357449,-0.101984,-0.060876,47.391914
13,2022,37.602216,12.400638,7909.672499,26.152944,8.435067,32.806343,257.848034,2.461603,195.337933,...,18.793683,16.750299,5.802567,4.908465,58.529693,1.375557,61.795719,-0.111639,-0.061410,46.964066
14,2023,38.421521,12.663142,7929.427890,26.212928,8.442711,33.206110,256.478315,2.491838,195.343348,...,18.631933,16.489790,5.707559,4.927806,58.761324,1.361929,61.233988,-0.121293,-0.061944,46.536218
15,2024,39.240827,12.925646,7949.183281,26.272911,8.450355,33.605878,255.108595,2.522072,195.348763,...,18.470183,16.229280,5.612552,4.947146,58.992956,1.348300,60.672258,-0.130947,-0.062478,46.108371
16,2025,40.060132,13.188151,7968.938673,26.332895,8.457999,34.005646,253.738876,2.552307,195.354178,...,18.308433,15.968771,5.517544,4.966487,59.224587,1.334672,60.110527,-0.140601,-0.063012,45.680523
17,2026,40.879438,13.450655,7988.694064,26.392878,8.465644,34.405413,252.369156,2.582542,195.359594,...,18.146682,15.708261,5.422537,4.985828,59.456219,1.321043,59.548796,-0.150255,-0.063546,45.252675
18,2027,41.698743,13.713159,8008.449455,26.452862,8.473288,34.805181,250.999437,2.612776,195.365009,...,17.984932,15.447752,5.327529,5.005168,59.687850,1.307415,58.987066,-0.159909,-0.064080,44.824828
19,2028,42.518049,13.975663,8028.204847,26.512846,8.480932,35.204948,249.629718,2.643011,195.370424,...,17.823182,15.187242,5.232522,5.024509,59.919482,1.293786,58.425335,-0.169563,-0.064615,44.396980
20,2029,43.337354,14.238168,8047.960238,26.572829,8.488576,35.604716,248.259998,2.673245,195.375839,...,17.661432,14.926732,5.137514,5.043849,60.151113,1.280157,57.863605,-0.179217,-0.065149,43.969132
21,2030,44.156659,14.500672,8067.715629,26.632813,8.496221,36.004484,246.890279,2.703480,195.381254,...,17.499682,14.666223,5.042506,5.063190,60.382745,1.266529,57.301874,-0.188871,-0.065683,43.541285

In [58]:
# Checking data types and columns
USA_Annual_AVG_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year                      22 non-null     int64
 1   maternal_mortality_ratio  22 non-null     float64
 2   diabetes_val              22 non-null     float64
 3   prem_death_val            22 non-null     float64
 4   phys_inac_val             22 non-null     float64
 5   low_birthweight_val       22 non-null     float64
 6   obesity_val               22 non-null     float64
 7   cardio_death_val          22 non-null     float64
 8   medicare                  22 non-null     float64
 9   cancer_death_val          22 non-null     float64
 10  chlamydia_val             22 non-null     float64
 11  child_pov_val             22 non-null     float64
 12  smoking_val               22 non-null     float64
 13  infant_mort_val           22 non-null     float64
 14  income_ineq_val           22 non-null     float64
 15  dentists_val              22 non-null     float64
 16  prem_death_ri_val         22 non-null     float64
 17  dent_vis_val              22 non-null     float64
 18  all_outcomes_val          22 non-null     float64
 19  all_determs_val           22 non-null     float64
 20  health_stat_fem_val       22 non-null     float64
dtypes: float64(20), int64(1)
memory usage: 3.7 KB

### Saving Final Combined Annual Averages DataFrame to CSV

In [59]:
# Saving concatenated dataframes into a csv file
USA_Annual_AVG_df.to_csv("../Resources/final_combined_avg_2009_2030.csv", index=False, header=True, float_format='%.2f')